
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 29 13:27:11 EDT 2015
//----------------------------------------------------

package mahimahi.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 42;
  public static final int LBRACKET = 16;
  public static final int TONE = 26;
  public static final int COLOR_LITERAL = 40;
  public static final int LPAREN = 12;
  public static final int SEMI = 18;
  public static final int INT = 20;
  public static final int MINUS = 3;
  public static final int STATIC = 34;
  public static final int RPAREN = 13;
  public static final int NOT = 9;
  public static final int AND = 7;
  public static final int LT = 8;
  public static final int COMMA = 10;
  public static final int CLASS = 36;
  public static final int MEGGYSETPIXEL = 48;
  public static final int BUTTON_LITERAL = 41;
  public static final int PLUS = 2;
  public static final int ASSIGN = 5;
  public static final int MAIN = 28;
  public static final int IF = 29;
  public static final int THIS = 35;
  public static final int DOT = 11;
  public static final int MEGGYGETPIXEL = 52;
  public static final int TONE_LITERAL = 43;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 33;
  public static final int RBRACKET = 17;
  public static final int EQUAL = 6;
  public static final int TRUE = 44;
  public static final int STRING_TYPE = 22;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MEGGYSETAUXLEDS = 49;
  public static final int VOID = 23;
  public static final int MEGGYTONESTART = 50;
  public static final int COLOR = 24;
  public static final int BYTE = 21;
  public static final int IMPORT = 46;
  public static final int TIMES = 4;
  public static final int MEGGYCHECKBUTTON = 53;
  public static final int LBRACE = 14;
  public static final int ELSE = 30;
  public static final int WHILE = 31;
  public static final int PUBLIC = 32;
  public static final int RBRACE = 15;
  public static final int EXTENDS = 37;
  public static final int MEGGYDELAY = 51;
  public static final int FALSE = 45;
  public static final int MEGGY = 47;
  public static final int BUTTON = 25;
  public static final int INT_LITERAL = 39;
  public static final int IDENTIFIER = 27;
}

